"""company members table

Revision ID: f60ef54bc8fb
Revises: debbb35cf04b
Create Date: 2023-03-12 15:09:58.242673

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60ef54bc8fb'
down_revision = 'debbb35cf04b'
branch_labels = None
depends_on = None

ROLES = [
    ('member', 'Member'),
    ('owner', 'Owner')
]

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sqlalchemy_utils.types.choice.ChoiceType(ROLES), default='member', nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_members_id'), 'company_members', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_members_id'), table_name='company_members')
    op.drop_table('company_members')
    # ### end Alembic commands ###
