"""attempt score

Revision ID: 0d241c289ebe
Revises: 14780a46f085
Create Date: 2023-03-26 20:49:05.634807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d241c289ebe'
down_revision = '14780a46f085'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempts', 'score')
    # ### end Alembic commands ###
