"""Changed company title to name

Revision ID: 2ab6dc64e371
Revises: 697b5076a5dd
Create Date: 2023-03-01 14:53:57.215199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab6dc64e371'
down_revision = '697b5076a5dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('companies', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('companies', 'name')
    # ### end Alembic commands ###
