"""

Revision ID: d0a17137dc24
Revises: 2ab6dc64e371
Create Date: 2023-03-03 12:01:27.317191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a17137dc24'
down_revision = '2ab6dc64e371'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
